services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: APP
    image: laravel_app
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8989:80"                            # Assurez-vous que les ports sont correctement formatés
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: bd
    restart: always
    ports:
      - "3306:3306"                          # Correction de la déclaration des ports
    environment:
      MYSQL_ROOT_PASSWORD: password          # Mot de passe root MySQL
      MYSQL_DATABASE: laravel                # Nom de la base de données
      SERVICE_TAGS: "dev"                    # Ce paramètre n'est pas nécessaire ici, mais ok
      SERVICE_NAME: mysql                     # Ce paramètre n'est pas nécessaire ici, mais ok
    volumes:
      - db_data:/var/lib/mysql               # Volume persistant pour la base de données
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"                            # Expose phpMyAdmin sur le port 8080
    environment:
      PMA_HOST: db                           # Le service MySQL
      PMA_USER: root                         # Utilisateur MySQL
      PMA_PASSWORD: password                  # Mot de passe root
    networks:
      - laravel

volumes:
  db_data:
    driver: local

networks:
  laravel:
    driver: bridge
